### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by ScottDWagner** [erossignon/node-occ#11]
I am getting this error trying to install this.

npm install node-occ
npm WARN package.json Node_OCC@0.0.0 No repository field.
> node-occ@0.0.4 install C:\Users\Scott\Source\Workspaces\Node-OCC\Node-OCC\Node-OCC\node_modules\node-occ
> node-gyp rebuild
C:\Users\Scott\Source\Workspaces\Node-OCC\Node-OCC\Node-OCC\node_modules\node-occ>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
gyp
npm ERR! node-occ@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-occ@0.0.4 install script.
npm ERR! This is most likely a problem with the node-occ package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-occ
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-occ"
npm ERR! cwd C:\Users\Scott\Source\Workspaces\Node-OCC\Node-OCC\Node-OCC
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
install node-occ completed with errors

**Comment by erossignon** [comment]
version has evolved significantly since this issue was raised. and mechanism to build under windows or ubuntu have been stabilized.
