### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined(Node.js)

### ISSUE THREAD

**Issue by dev1intellial** [erossignon/node-occ#13]
This example showing creation of basic shapes using node.js ...
				
```javascript
var occ = require('occ')
// construct a box
var box = occ.makeBox([0,0,0],[100,100,50])
// construct a cylinder
var cyl = occ.makeCylinder([50,50,-10],[50,50,60],40)
// cut the box with cylinder
box = occ.cut(box,cyl)
// save result to a STEP file
occ.writeSTEP("somefile.step",box)
```

I am going to run the above program using node.js but I am getting this error ..

```
D:\node-file>node test.js
adding occ.Mesh.prototype.toJSON function
D:\node-file\node_modules\occ\lib\mesh.js:17
 occ.Mesh.prototype.toJSON = function() {
TypeError: Cannot read property 'prototype' of undefined
at Object.exports.init (D:\node-file\node_modules\occ\lib\mesh.js:17:11)
at Object.<anonymous> (D:\node-file\node_modules\occ\lib\occ.js:10:19)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (D:\node-file\test.js:1:73)
at Module._compile (module.js:460:26)
```					
How to solve this issue? Any suggestion?

**Comment by erossignon** [comment]
what is the result of:

    git clone https://github.com/erossignon/node-occ.git
    cd node-occ
    npm install
    npm test

**Comment by dev1intellial** [comment]
Thanks for your quick response.
I have downloaded node-occ.git and followed your steps but not able to installed module. I have attached both cmd error and debug.log images. 

CMD log:
![cmd_error](https://cloud.githubusercontent.com/assets/475509/6478889/e999b7ce-c261-11e4-8f72-95e5836ec963.png)

Debug log:
![npm-debug](https://cloud.githubusercontent.com/assets/475509/6478890/e99bc302-c261-11e4-8d3d-8fddd8fa1eed.png)

From cmd error I found that it requires "VCBuild.exe" and for that it shows two options, either Microsoft Windows SDK or  Microsoft Visual Studio 2008. 
I have already installed vs2012 and I open up "\build\binding.sln" and try to build project but gives numbers of files missing error at compile time and the below is what I get when tried to build project.

![vserror](https://cloud.githubusercontent.com/assets/475509/6478958/1fe87c92-c263-11e4-8e90-5a1523dad5fd.png)

What I'm missing or doing wrong to install desire modules? Please help me out.

**Comment by erossignon** [comment]
Hi,
I have improved the [wiki page](https://github.com/erossignon/node-occ/wiki) that describes the steps to follow to get the prerequisite installed on your computer ( Visual Studio , cmake, OpenCascade libraires )

**Comment by dev1intellial** [comment]
I have downloaded all the pre-requistes software and followed your steps but not able to installed module. 

c:\tools\cmake\bin\cmake  -D OCE_INSTALL_PREFIX:STRING='C:/OCE-13' -D OCE_DRAW:BOOLEAN=FALSE -D OCE_OCAF:BOOLEAN=FALSE -D  OCE_VISUALISATION:BOOLEAN=FALSE -D OCE_DISABLE_X11:BOOLEAN=TRUE -D OCE_USE_PCH:BOOLEAN=TRUE  ../oce

Above command ran successfully but when I fired msbuildoce.sln this command and its completed with 37 warning and one error. I have attached msbuild error..  

MsBuils error:

![msbuilderror](https://cloud.githubusercontent.com/assets/475509/6500146/95968c70-c32d-11e4-9c9d-926952f83567.png)

**Comment by erossignon** [comment]
a build.bat script has been provided, this script is used by the AppVeyor continuous integration platform but can also be used to build node-occ on your windows computer.
Make sure you have Visual Studio 2013 and git installed first.
