### ISSUE TITLE
Color issue in Python.

### ISSUE THREAD

**Issue by dev1intellial** [erossignon/node-occ#14]
First of all I am using this below code to read data from STEP file to generate 3D object but I am not able to set the color of this shape.
Every time its showing only default color. 

				from __future__ import print_function
				from OCC.TCollection import TCollection_ExtendedString
				from OCC.XCAFDoc import *
				from OCC.TDocStd import Handle_TDocStd_Document
				from OCC.TopoDS import *
				from OCC.Quantity import *
				from OCC.XCAFApp import XCAFApp_Application
				from OCC.XCAFDoc import (XCAFDoc_DocumentTool_ShapeTool,
										 XCAFDoc_DocumentTool_ColorTool,
										 XCAFDoc_DocumentTool_LayerTool,
										 XCAFDoc_DocumentTool_MaterialTool,
										 XCAFDoc_ColorGen)
				from OCC.STEPCAFControl import STEPCAFControl_Reader
				from OCC.Quantity import Quantity_Color
				from OCC.IFSelect import IFSelect_RetDone
				from OCC.TDF import TDF_LabelSequence

				from OCC.Display.SimpleGui import init_display
				from OCC.Display.WebGl import webgl_renderer

				filename = './models/test.STEP'
				_shapes = []

				# create an handle to a document
				h_doc = Handle_TDocStd_Document()

				# Create the application
				app = XCAFApp_Application.GetApplication().GetObject()
				app.NewDocument(TCollection_ExtendedString("MDTV-CAF"), h_doc)

				# Get root assembly
				doc = h_doc.GetObject()
				h_shape_tool = XCAFDoc_DocumentTool_ShapeTool(doc.Main())
				l_colors = XCAFDoc_DocumentTool_ColorTool(doc.Main())
				l_layers = XCAFDoc_DocumentTool_LayerTool(doc.Main())
				l_materials = XCAFDoc_DocumentTool_MaterialTool(doc.Main())

				step_reader = STEPCAFControl_Reader()
				step_reader.SetColorMode(True)
				step_reader.SetLayerMode(True)
				step_reader.SetNameMode(True)
				step_reader.SetMatMode(True)

				status = step_reader.ReadFile(filename)
				if status == IFSelect_RetDone:
					step_reader.Transfer(doc.GetHandle())
				comps = TDF_LabelSequence()
				labels = TDF_LabelSequence()
				color_labels = TDF_LabelSequence()

				#print(h_shape_tool.GetObject().UpdateAssembly(labels))

				shape_tool = h_shape_tool.GetObject()
				h_shape_tool.GetObject().GetFreeShapes(labels)

				print("Number of shapes at root :%i" % labels.Length())
				for i in range(labels.Length()):
					sub_shapes_labels = TDF_LabelSequence()
					print("Is Assembly :", shape_tool.IsAssembly(labels.Value(i+1)))
					sub_shapes = shape_tool.GetSubShapes(labels.Value(i+1), sub_shapes_labels)
					l_colors.GetObject().GetColors(color_labels)
					print("Number of subshapes in the assemly :%i" % sub_shapes_labels.Length())
					for j in range(20):
						a_shape = h_shape_tool.GetObject().GetShape(sub_shapes_labels.Value(j+1))
						#l_colors.GetObject().GetColors(color_labels)
						#l_colors.GetObject().SetColor(Quantity_Color(Quantity_NOC_BLACK))
						l_colors.GetObject().UnSetColor
						red = Quantity.Quantity_Color(Quantity.Quantity_NOC_RED)
						green = Quantity.Quantity_Color(Quantity.Quantity_NOC_GREEN)
						l_colors.GetObject().SetColor(a_shape, red, XCAFDoc_ColorGen)
						l_colors.GetObject().SetColor(a_shape, green, XCAFDoc_ColorGen)
						
						_shapes.append(a_shape)
						#print(sub_shapes_labels.Value(j+1).Data())

				#
				# Display
				#
				display, start_display, add_menu, add_function_to_menu = init_display()
				#display.FitAll()
				#display.DisplayColoredShape(_shapes, update=True)
				display.DisplayShape(_shapes, update=True)
				start_display()

				#my_renderer = webgl_renderer.WebGlRenderer(background_color="#123345")
				#my_renderer.DisplayShape(a_shape)

Any suggestion? Thanx

**Comment by erossignon** [comment]
Should this issue be posted in python-occ instead ?
