### ISSUE TITLE
Certain operations are defined but not implemented

### ISSUE THREAD

**Issue by skbizport** [erossignon/node-occ#16]
Hi,

A few operations have not been implemented and exposed, E.g. applyTransform or scale in Base.h. Any plans of implementing them?

Also, will be great if you could provide some examples of how to extrude faces?

Regards

**Comment by erossignon** [comment]
Thank you for noticing that applyTransform is not exposed, I shall fix this.

extrude face can be achieve with makePrism , have a look at https://github.com/erossignon/node-occ/blob/master/lib/shapeFactory.js

**Comment by skbizport** [comment]
That's great. Appreciate.
