### ISSUE TITLE
Node V4+

### ISSUE THREAD

**Issue by jloveric** [erossignon/node-occ#22]
Hi, I just tried this out with Node V4.1 on Ubuntu.  It fails due to Nan issues.  Actually tons of javascript codes have failed with the shift to Node V4 with the same issue.  Just a couple of lines of the error provided below...

make: Entering directory '/home/john/PROJECTS/OpenCascadeJS/node-occ/build'
  CXX(target) Release/obj.target/occ/src/Base.o
In file included from ../src/NodeV8.h:17:0,
                 from ../src/Base.h:2,
                 from ../src/Base.cc:1:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
...

**Comment by eric-schleicher** [comment]
Hi @jloveric & @erossignon .  Also I got the same result with `node -v : v4.2.1`.  I've very interested in getting this to work.  Is there a version of node that this is known to work with?

-Eric

**Comment by erossignon** [comment]
N ow fixed

**Comment by zqqiang** [comment]
Hi @erossignon  I think you should update https://github.com/erossignon/node-occ/wiki#pre-requistes to avoid user misunderstand if they update to latest release.
