### ISSUE TITLE
help with load brep

### ISSUE THREAD

**Issue by lorinma** [erossignon/node-occ#23]
Hi Etienne, 

Sorry to post an issue here, I don't know where to ask a question.
I've setup the server and can create shapes using the web command lie.

I'm not familiar with node-js, could you please show an simple example about how to load a brep file (exported from occ) and render it in the web?

Thanks so much!

Ling

**Comment by erossignon** [comment]
# go to sample folder
$ cd sample
launch demo app
$node app.ps 

# try visiting http://localhost:3000/viewer

click browse and select a STEP file for instance.

enjoy

**Comment by lorinma** [comment]
Thanks. I had managed to make it and built a docker image.

Ling

On Tue, Feb 23, 2016 at 8:34 PM Etienne <notifications@github.com> wrote:

> go to sample folder
>
> $ cd sample
> launch demo app
> $node app.ps
> try visiting http://localhost:3000/viewer
>
> click browse and select a STEP file for instance.
>
> enjoy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erossignon/node-occ/issues/23#issuecomment-187832311>.
>
-- 
------------------------------------------------------------------
Ling Ma <http://www.linkedin.com/pub/ling-ma/1a/761/a23>, Postdoctoral
Fellow

Virtual Construction Lab
National Building Research Institute
Faculty of Civil and Environmental Engineering
Technion - Israel Institute of Technology
